server:
  port: 8001

cloud:
  aws:
    credentials:
      access-key: AKIA4GTPWBDNZ45XCSHB
      secret-key: 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
    s3:
      bucket: linkyb-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

spring:

  mail:
    host: smtp.gmail.com
    port: 587
    username: ingistak
    password: kyosqtxydxqvktkc
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://linkyb.csnhnz4hejhb.ap-northeast-2.rds.amazonaws.com :3306/LinkyB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: 1q2w3e4r!

  jpa:
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: false

  thymeleaf:
    cache: false



jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400